src/TFCLPortal.Web.Mvc/Controllers/ManagmentCommitteeDecisionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Abp.Domain.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TFCLPortal.Applications;
using TFCLPortal.Applications.Dto;
using TFCLPortal.Authorization.Users;
using TFCLPortal.Controllers;
using TFCLPortal.EntityFrameworkCore;
using TFCLPortal.FinalWorkflows;
using TFCLPortal.FinalWorkflows.Dto;
using TFCLPortal.ManagmentCommitteeDecisions;
using TFCLPortal.ManagmentCommitteeDecisions.Dto;
using TFCLPortal.NotificationLogs;
using TFCLPortal.Users;
using TFCLPortal.Web.Models.McModels;

namespace TFCLPortal.Web.Controllers
{
    public class ManagmentCommitteeDecisionsController : TFCLPortalControllerBase
    {
        private readonly IUserAppService _userAppService;
        private readonly IApplicationAppService _applicationAppService;
        private readonly IManagmentCommitteeDecisionAppService _managmentCommitteeDecisionAppService;
        private readonly IRepository<ManagmentCommitteeDecision, int> _managmentCommitteeDecisionRepository;
        private readonly UserManager _userManager;
        private readonly IFinalWorkflowAppService _finalWorkflowAppService;
        private readonly INotificationLogAppService _notificationLogAppService;


        public ManagmentCommitteeDecisionsController(IUserAppService userAppService, INotificationLogAppService notificationLogAppService, IFinalWorkflowAppService finalWorkflowAppService, UserManager userManager, IRepository<ManagmentCommitteeDecision, int> managmentCommitteeDecisionRepository, IApplicationAppService applicationAppService, IManagmentCommitteeDecisionAppService managmentCommitteeDecisionAppService)
        {
            _userAppService = userAppService;
            _notificationLogAppService = notificationLogAppService;
            _applicationAppService = applicationAppService;
            _managmentCommitteeDecisionAppService = managmentCommitteeDecisionAppService;
            _managmentCommitteeDecisionRepository = managmentCommitteeDecisionRepository;
            _userManager = userManager;
            _finalWorkflowAppService = finalWorkflowAppService;
        }

        // GET: ManagmentCommitteeDecisions
        public IActionResult Index()
        {
            int userid = (int)_userManager.AbpSession.UserId;
            var applications = _applicationAppService.GetShortApplicationList(ApplicationState.BCC_Approved, 0);

            List<Applicationz> returnList = new List<Applicationz>();


            if (userid != 0)
            {
                if (userid == 66) //Manager (OPS)
                {
                    foreach (var app in applications)
                    {
                        var decision = _managmentCommitteeDecisionRepository.GetAllList(x => x.ApplicationId == app.Id && x.fk_userid == userid);
                        if (decision.Count == 0)
                        {
                            returnList.Add(app);
                        }
                    }
                }
                else if (userid == 69) //Manager (F&A)
                {
                    foreach (var app in applications)
                    {
                        var decision = _managmentCommitteeDecisionRepository.GetAllList(x => x.ApplicationId == app.Id);
                        if (decision.Count > 0)
                        {
                            if (!decision.Where(x => x.fk_userid == userid).Any())
                            {
                                if (decision.Where(x => x.fk_userid == 66 && x.Decision == "Authorized").Any())
                                {
                                    returnList.Add(app);
                                }
                            }
                        }
                    }
                }
                else if (userid == 67) //CEO
                {
                    foreach (var app in applications)
                    {
                        var decision = _managmentCommitteeDecisionRepository.GetAllList(x => x.ApplicationId == app.Id);
                        if (decision.Count > 0)
                        {
                            if (!decision.Where(x => x.fk_userid == userid).Any())
                            {
                                if (decision.Where(x => x.fk_userid == 66 && x.Decision == "Authorized").Any() && decision.Where(x => x.fk_userid == 69 && x.Decision == "Authorized").Any())
                                {
                                    returnList.Add(app);
                                }
                            }
                        }
                    }
                }
                else if (userid == 2) //Admin
                {
                    foreach (var app in applications)
                    {
                        returnList.Add(app);
                    }
                }
            }
            else
            {

            }




            var mcs = _managmentCommitteeDecisionAppService.GetManagmentCommitteeDecisionList();

            McModel mc = new McModel();
            mc.applications = returnList;
            mc.decisions = mcs;

            return View(mc);
        }
        public async Task<IActionResult> CreateMC(int Id)
        {
            int userid = (int)_userManager.AbpSession.UserId;

            if (userid != 0)
            {
                ManagmentCommitteeDecision decision = new ManagmentCommitteeDecision();
                decision.ApplicationId = Id;
                decision.fk_userid = userid;
                decision.Decision = "Authorized";

                _managmentCommitteeDecisionRepository.Insert(decision);
                CurrentUnitOfWork.SaveChanges();

                var appData = _applicationAppService.GetApplicationById(Id);
                if (appData != null)
                {
                    if (userid == 66)
                    {
                        await _notificationLogAppService.SendNotification(69, appData.ClientID + " is waiting for your approval", "Kindly view BCC Approved Applications.");
                    }
                    else if (userid == 69)
                    {
                        await _notificationLogAppService.SendNotification(67, appData.ClientID + " is waiting for your approval", "Kindly view BCC Approved Applications. ");
                    }
                }
            }

            var list = _managmentCommitteeDecisionRepository.GetAllList(x => x.ApplicationId == Id && x.Decision == "Authorized");

            if (list.Where(x => x.fk_userid == 66).Any())
            {
                if (list.Where(x => x.fk_userid == 69).Any())
                {
                    if (list.Where(x => x.fk_userid == 67).Any())
                    {
                        _applicationAppService.ChangeApplicationState(ApplicationState.MC_Authorized, Id, "");

                        CreateFinalWorkflowDto fWobj = new CreateFinalWorkflowDto();
                        fWobj.ApplicationId = Id;
                        fWobj.Action = "Application Authorized By Management Committee";
                        fWobj.ActionBy = userid;
                        fWobj.ApplicationState = ApplicationState.MC_Authorized;
                        fWobj.isActive = true;

                        await _finalWorkflowAppService.CreateFinalWorkflow(fWobj);
                    }
                }
            }


            return RedirectToAction("Index");
        }

        public async Task<IActionResult> CreateMCdecline(int Id,string Reason)
        {
            var app = _applicationAppService.GetApplicationById(Id);

            if(app!=null)
            {
                CreateFinalWorkflowDto fWobj = new CreateFinalWorkflowDto();
                fWobj.ApplicationId = app.Id;
                fWobj.Action = "Decline";
                fWobj.ActionBy = (int)AbpSession.UserId;
                fWobj.ApplicationState = ApplicationState.Decline;
                fWobj.isActive = true;

                _finalWorkflowAppService.CreateFinalWorkflow(fWobj);

                _applicationAppService.ChangeApplicationState(ApplicationState.Decline, app.Id, Reason);
            }


            return RedirectToAction("Index");
        }

    }
}

src/TFCLPortal.Web.Mvc/Views/ManagmentCommitteeDecisions/Create.cshtml
@model TFCLPortal.ManagmentCommitteeDecisions.ManagmentCommitteeDecision

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_NewLayout.cshtml";
}

<h2>Create</h2>

<h4>ManagmentCommitteeDecision</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="fk_userid" class="control-label"></label>
                <input asp-for="fk_userid" class="form-control" />
                <span asp-validation-for="fk_userid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationId" class="control-label"></label>
                <input asp-for="ApplicationId" class="form-control" />
                <span asp-validation-for="ApplicationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Decision" class="control-label"></label>
                <input asp-for="Decision" class="form-control" />
                <span asp-validation-for="Decision" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reason" class="control-label"></label>
                <input asp-for="Reason" class="form-control" />
                <span asp-validation-for="Reason" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="DeleterUserId" class="control-label"></label>
                <input asp-for="DeleterUserId" class="form-control" />
                <span asp-validation-for="DeleterUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeletionTime" class="control-label"></label>
                <input asp-for="DeletionTime" class="form-control" />
                <span asp-validation-for="DeletionTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastModificationTime" class="control-label"></label>
                <input asp-for="LastModificationTime" class="form-control" />
                <span asp-validation-for="LastModificationTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastModifierUserId" class="control-label"></label>
                <input asp-for="LastModifierUserId" class="form-control" />
                <span asp-validation-for="LastModifierUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationTime" class="control-label"></label>
                <input asp-for="CreationTime" class="form-control" />
                <span asp-validation-for="CreationTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatorUserId" class="control-label"></label>
                <input asp-for="CreatorUserId" class="form-control" />
                <span asp-validation-for="CreatorUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/TFCLPortal.Web.Mvc/Views/ManagmentCommitteeDecisions/Delete.cshtml
@model TFCLPortal.ManagmentCommitteeDecisions.ManagmentCommitteeDecision

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_NewLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ManagmentCommitteeDecision</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.fk_userid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.fk_userid)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Decision)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Decision)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Reason)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Reason)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DeleterUserId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DeleterUserId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DeletionTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DeletionTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastModificationTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastModificationTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastModifierUserId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastModifierUserId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreationTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreationTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatorUserId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatorUserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/TFCLPortal.Web.Mvc/Views/ManagmentCommitteeDecisions/Details.cshtml
@model TFCLPortal.ManagmentCommitteeDecisions.ManagmentCommitteeDecision

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_NewLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ManagmentCommitteeDecision</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.fk_userid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.fk_userid)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Decision)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Decision)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Reason)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Reason)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DeleterUserId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DeleterUserId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DeletionTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DeletionTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastModificationTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastModificationTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastModifierUserId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastModifierUserId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreationTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreationTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatorUserId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatorUserId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/TFCLPortal.Web.Mvc/Views/ManagmentCommitteeDecisions/Index.cshtml
@model TFCLPortal.Web.Models.McModels.McModel

@{ int i = 0;}
@{
    int n = 0;
    List<TFCLPortal.ManagmentCommitteeDecisions.Dto.ManagmentCommitteeDecisionListDto> decisions = new List<TFCLPortal.ManagmentCommitteeDecisions.Dto.ManagmentCommitteeDecisionListDto>();
}

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewLayout.cshtml";
}
<style>
    .dataTable tr th, .dataTable tr td {
        text-align: center;
        background-image: none;
        position: relative;
    }

    .dropdown-item {
        font-size: 11px;
        color: #416a2c;
        text-align: left;
    }

    .pageloader {
        position: fixed;
        left: 0px;
        top: 0px;
        width: 100%;
        height: 100%;
        z-index: 9999;
        background: url('/Theame/images/loader.gif') 50% 50% no-repeat rgb(249, 249, 249);
        opacity: .8;
    }
</style>
<!-- ### $App Screen Content ### -->
<main class='main-content bgc-grey-100' style="padding-top:50px">
    <div class="pageloader d-none"></div>

    <div class="row page-title">
        <div class="col-md-6 text-left">
            <h4 class="page-title-text">
                BCC Approved Applications
            </h4>
            <h6 class="page-title-breadcrumbs">
                <a href="~/Dashboard/Dashboard">Home</a> > Management Committee  > BCC Approved Applications
            </h6>
        </div>
        <div class="col-md-6 text-right">
            @*<button class="btn btn-sm btn-outline-success" onclick="$('#filterForm').toggle();"><i class="fa fa-filter"></i> Filter Records</button>*@
            <a href="~/Dashboard/Dashboard" class="btn btn-sm btn-outline-success bg1 eft-1" title="Back"><i class="fa fa-angle-double-left"></i> Back To Home </a>
        </div>
    </div>
    <div class="card p-10 mB-20">
        @*<p>
                <a asp-action="Create">Create New</a>
            </p>*@
        <table class=" dataTable table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>
                        Sr
                    </th>
                    <th>
                        CLIENT ID
                    </th>
                    <th>
                        APPLICANT / RESPONDENT NAME
                    </th>
                    <th>
                        Client / School / Business Name
                    </th>

                    <th colspan="1">
                        Approve
                    </th>
                    <th colspan="1">
                        Decline
                    </th>
                    <th colspan="3">
                        Details
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.applications)
                {
                    <tr>
                        <td> @{i = i + 1;} @i</td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ClientID)

                            @(item.isEnhancementApplication==true ? " (E)" : "")
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ClientName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SchoolName)
                        </td>

                        <td>
                            <a onclick="if (confirm('Are you sure?')) { window.location.href = '@Url.Action("CreateMC", "ManagmentCommitteeDecisions", new { Id = item.Id })'; }"><i class="fa fa-check-circle text-success"></i> Approve </a>
                            @*<a asp-action="CreateMC" asp-route-id="@item.Id" onclick="confirm('Are You Sure?');"><i class="fa fa-check-circle"></i> Approve </a>*@
                        </td>
                        <td>
                            @*<a onclick="if (confirm('Are you sure you want to decline this application?')) { window.location.href = '@Url.Action("CreateMC", "ManagmentCommitteeDecisions", new { Id = item.Id })'; }"><i class="fa fa-times-circle text-danger"></i> Decline </a>*@
                            <a onclick="DeclineApp(@item.Id)"><i class="fa fa-times-circle text-danger"></i> Decline </a>
                            @*<a asp-action="CreateMC" asp-route-id="@item.Id" onclick="confirm('Are You Sure?');"><i class="fa fa-check-circle"></i> Approve </a>*@
                        </td>
                        <td>
                            @if (item.ProductType == 1 || item.ProductType == 2)
                            {
                                <a href="/Dashboard/Application?id=@item.Id" target="_blank"><i class="fa fa-search"></i> View Details</a>
                            }
                            else if (item.ProductType == 8 || item.ProductType == 9)
                            {
                                <a href="/Dashboard/TdsApplication?id=@item.Id" target="_blank"><i class="fa fa-search"></i> View Details</a>
                            }
                        </td>
                        <td>
                            <a href="/McrcDecisions/Index?ApplicationId=@item.Id" target="_blank"><i class="fa fa-comment"></i> MCRC Decisions</a>
                        </td>
                        <td>
                            <a href="/BCCDecisions/Index?ApplicationId=@item.Id" target="_blank"><i class="fa fa-comment"></i> BCC Decisions</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="card p-10 mB-20">

        <div class="row page-title mt-3 mb-3">
            <div class="col-md-6 text-left">
                <h4 class="page-title-text" style="text-transform:capitalize">
                    Applied Decisions
                </h4>
            </div>
        </div>
        <table id="dataTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>
                        Sr
                    </th>
                    <th>
                        CLIENT ID
                    </th>
                    <th>
                        APPLICANT / RESPONDENT NAME
                    </th>
                    <th>
                        Client / School / Business Name
                    </th>
                    <th>
                        State
                    </th>
                    <th>
                        Authorization By (No Of MCM)
                    </th>
                    <th>
                        Decision Date
                    </th>
                    <th>
                        BCC Approval Date
                    </th>
                    <th>
                        Details
                    </th>
                </tr>
            </thead>
            <tbody>

                @foreach (var Outeritem in Model.decisions.GroupBy(x => x.ApplicationId).ToList())
                {

                    var itemDecisions = Model.decisions.Where(x => x.ApplicationId == Outeritem.Key).ToList();

                    //if(itemDecisions.Any(x=>x.Decision==""))

                    var item = itemDecisions.FirstOrDefault();


                        <tr>
                            <td> @{n = n + 1;} @n</td>
                            <td>
                                @item.ClientID
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ClientName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SchoolName)
                            </td>
                            @*<td>
                        @Html.DisplayFor(modelItem => item.State)
                    </td>*@
                            @if (Outeritem.Count() < 3)
                            {
                                <td>Pending</td>
                            }
                            else
                            {
                                <td>Authorized</td>
                            }

                            <td width="10%">
                                @if (Outeritem.Count() < 3)
                                {
                                    @(Outeritem.Count())
                                }
                                else
                                {
                                    @(3)
                                }
                            </td>
                            <td>@item.CreationTime.ToString("dd MMM yyyy hh:mm tt")</td>
                            <td>@(item.BccApprovalDate==null? "--": String.Format("{0:dd MMM yyyy hh:mm tt}", item.BccApprovalDate))</td>
                            <td>
                                <div class="dropdown">
                                    <a class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-list"></i>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        @if (item.productType == 1 || item.productType == 2)
                                        {
                                            <a class="dropdown-item" href="/Dashboard/Application?id=@item.ApplicationId" target="_blank"><i class="fa fa-search"></i> View Details</a>
                                        }
                                        else if (item.productType == 8 || item.productType == 9)
                                        {
                                            <a class="dropdown-item" href="/Dashboard/TdsApplication?id=@item.ApplicationId" target="_blank"><i class="fa fa-search"></i> View Details</a>
                                        }
                                        <a class="dropdown-item" href="/McrcDecisions/Index?ApplicationId=@item.ApplicationId" target="_blank"><i class="fa fa-comment"></i> MCRC Decisions</a>
                                        <a class="dropdown-item" href="/BCCDecisions/Index?ApplicationId=@item.ApplicationId" target="_blank"><i class="fa fa-comment"></i> BCC Decisions</a>

                                    </div>
                                </div>
                            </td>
                        </tr>
                }
            </tbody>
        </table>
    </div>

    @*<table id="dataTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>
                        Details
                    </th>
                    <th>
                        Details
                    </th>
                </tr>
            </thead>
            <tbody>




                    <tr>
                        <td> @item.Key</td>

                        <td> @(item.Count())</td>
                    </tr>
            </tbody>
        </table>*@

</main>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<script>
    function DeclineApp(appid) {
        //let text;
        let msg = prompt("Please enter reason for decline:", "");
        $(".pageloader").toggleClass("d-none");

        if (msg == null || msg == "") {
            // text = "User cancelled the prompt.";
        } else {
            //text = msg;
            window.location.href = '../ManagmentCommitteeDecisions/CreateMCdecline?Id=' + appid + '&&Reason=' + msg;
        }
    }
</script>